---
helmDefaults:
  tillerless: true
  wait: false
releases:
  - name: mongo-scheduler-{{ requiredEnv "ENV" }}
    namespace: {{ requiredEnv "NS" }}
    chart: ./charts
    values:
    - ./charts/values/{{ requiredEnv "ENV" }}/values.yaml
