---
apiVersion: v1
kind: ReplicationController
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    app: {{ .Release.Name }}
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        app: {{ .Release.Name }}
    spec:
      serviceAccount: {{ .Release.Name }}-account
      automountServiceAccountToken: true
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.imageDetails.name }}:{{ .Values.imageDetails.version }}
        imagePullPolicy: {{ .Values.imageDetails.pullPolicy }}
        volumeMounts:
        - name: conf
          mountPath: /init
          readOnly: true
        env:
        - name: SNAME
          value: {{ .Release.Name }}
      volumes:
      - name: conf
        configMap:
          name: {{ .Release.Name }}-configmap
          defaultMode: 0755