---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  mongoScheduler.yaml: |
{{ toYaml .Values.config | indent 4 }}
  mongoScheduler.py: |
{{ .Files.Get "files/mongoScheduler.py" | indent 4 }}
  helpers.py: |
{{ .Files.Get "files/helpers.py" | indent 4 }}