apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-account
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-scheduler-as-kube-scheduler
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-account
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: system:kube-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-scheduler-as-volume-scheduler
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-account
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: system:volume-scheduler
  apiGroup: rbac.authorization.k8s.io